package Acme::CPANModulesBundle::Import::PerlAdvent::2018;

# DATE
# VERSION

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2018

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in
L<http://perladvent.org/2018/>. Visit the URL for the full contents.
