package Acme::CPANModules::Import::PerlAdvent::2018_12_03;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2018/2018-12-03.html] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Convert::ASN1"},{module=>"Cpanel::JSON::XS"},{module=>"Cpanel::JSON::XS::Type"},{module=>"JSON"},{module=>"JSON::PP"},{module=>"JSON::XS"},{module=>"XML::Compile::SOAP"}],summary=>"Modules mentioned in Perl Advent Calendar 2018 (day 03)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2018 (day 03)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2018/2018-12-03.html> (retrieved on 2018-12-30). Visit the URL for the full contents.

