package Acme::CPANModules::Import::PerlAdvent::2018_12_08;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2018/2018-12-08.html] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"DBD::MariaDB"},{module=>"DBD::Pg"},{module=>"DBD::SQLite"},{module=>"DBD::mysql"}],summary=>"Modules mentioned in Perl Advent Calendar 2018 (day 08)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2018 (day 08)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2018/2018-12-08.html> (retrieved on 2018-12-30). Visit the URL for the full contents.

