package Acme::CPANModules::Import::PerlAdvent::2018_12_13;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2018/2018-12-13.html] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Sub::Params"}],summary=>"Modules mentioned in Perl Advent Calendar 2018 (day 13)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2018 (day 13)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2018/2018-12-13.html> (retrieved on 2018-12-30). Visit the URL for the full contents.

