package Acme::CPANModules::Import::PerlAdvent::2018;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2018/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Memoize"},{module=>"Convert::ASN1"},{module=>"Cpanel::JSON::XS"},{module=>"Cpanel::JSON::XS::Type"},{module=>"JSON"},{module=>"JSON::PP"},{module=>"JSON::XS"},{module=>"XML::Compile::SOAP"},{module=>"Data::Rmap"},{module=>"Array::Sticky"},{module=>"Array::Sticky::INC"},{module=>"DBIx::Class"},{module=>"Text::CSV::Pivot"},{module=>"DBD::MariaDB"},{module=>"DBD::Pg"},{module=>"DBD::SQLite"},{module=>"DBD::mysql"},{module=>"App::sigfix"},{module=>"Dist::Zilla"},{module=>"Dist::Zilla::Plugin::Babble"},{module=>"PPR"},{module=>"Syntax::Keyword::Try"},{module=>"Moo"},{module=>"MooX::ShortHas"},{module=>"Moose"},{module=>"Mu"},{module=>"SVG"},{module=>"SVG::ChristmasTree"},{module=>"Sub::Params"},{module=>"Hash::Flatten"},{module=>"Mac::Glue"},{module=>"OAuth::Cmdline::Spotify"},{module=>"Spreadsheet::Read"},{module=>"Spreadsheet::WriteExcel"},{module=>"Test::Excel"},{module=>"Mojo::Promise"},{module=>"Mojo::URL"},{module=>"Mojo::UserAgent"},{module=>"Devel::hdb"},{module=>"ojo"},{module=>"Method::ParamValidator"},{module=>"Test::Exception"},{module=>"Try::Tiny"},{module=>"WWW::Google::Places"},{module=>"Context::Singleton"},{module=>"App::HTTPSThis"},{module=>"App::HTTPThis"},{module=>"B"},{module=>"Calendar::List"},{module=>"Future"},{module=>"App::ccdiff"}],summary=>"Modules mentioned in Perl Advent Calendar 2018"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2018

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2018/> (retrieved on 2018-12-30). Visit the URL for the full contents.

