package Acme::CPANModules::Import::PerlAdvent::2018_12_09;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2018/2018-12-09.html] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"App::sigfix"}],summary=>"Modules mentioned in Perl Advent Calendar 2018 (day 09)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2018 (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2018/2018-12-09.html> (retrieved on 2018-12-30). Visit the URL for the full contents.

