#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANModulesImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

my %add_modules = (
    # not linked
    "01" => ["Calendar::List"],
    "04" => ["B"],
    "14" => ["Future"],
    "15" => ["App::ccdiff"],
);

my %typos = (
    #'Perl::PrereqScanner::NotSoLite' => 'Perl::PrereqScanner::NotQuiteLite',
);

gen_curried_sub(
    'App::CreateAcmeCPANModulesImportModules::create_acme_cpanmodules_import_modules',
    {
        modules => [
            {
                name => '2018',
                url => "http://perladvent.org/2018/",
                extract_urls => [map {"http://perladvent.org/2018/2018-12-$_.html"} "01".."25"],
                summary => 'Modules mentioned in Perl Advent Calendar 2018',
                add_modules => [map {@$_} values %add_modules],
            },
            (map {
                +{
                    name => "2018_12_$_",
                    url => "http://perladvent.org/2018/2018-12-$_.html",
                    summary => "Modules mentioned in Perl Advent Calendar 2018 (day $_)",
                    add_modules => [@{ $add_modules{$_} // [] }],
                },
            } "01".."24"),
        ],
        typos => \%typos,
        ignore_empty => 1,
        namespace => 'Acme::CPANModules::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
